development:
  adapter: mysql2
  database: expert_development
  username: root
  password: local
  encoding: utf8
  host: localhost

test:
  adapter: mysql2
  database: expert_test
  username: root
  password: local
  encoding: utf8
  host: localhost
   
production:
  adapter: mysql2
  database: babrovka_exper31
  username: babrovka_exper31
  password: rbu9EqcI
  encoding: utf8
  host: mysql5.locum.ru
