development:
  adapter: mysql2
  database: expert_development
  username: root
  password: 
  encoding: utf8
  host: localhost

test:
  adapter: mysql2
  database: expert_test
  username: root
  password: 1
  encoding: utf8
  host: localhost
   
production:
  adapter: mysql2
  database: carexpert
  username: root
  password: carbagus
  encoding: utf8
  host: localhost
